# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
resources: 
  repositories: 
  - repository: templates 
    name: templates/templates 
    type: git 
    ref: main

trigger:
  - main
  - Reusable-pipelines
  - trivy-azuredevops-ext

jobs:
- job: Job1
  displayName: Run trivy via imported pipeline
  pool:
    vmImage: "ubuntu-latest"  
  
  steps:
  - task: trivy@1
    inputs:
      path: .
      aquaKey: $(AQUA_KEY)
      aquaSecret: $(AQUA_SECRET)
